on:
  pull_request:
    types:
      - opened
    branches:    
      - 'main'

jobs:
  betterscan_job:
   runs-on: ubuntu-latest
   name: Betterscan scan job
   steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: topcodersonline/betterscan-custom@v3
